<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Пользователь</title>

</head>

<body>
<div class="d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card" style="width: 18rem;">
        <img src="{{ user.image }}" class="card-img-top" alt="{{ user.name }}">
        <div class="card-body">
            <h5 class="card-title">{{ user.name }}</h5>
            <p class="card-text">{{ user.email }}</p>
            <a href="/users" class="btn btn-primary">Список пользователей</a>
        </div>
    </div>
</div>
</body>
</html>
